//go:build ignore

// Generate timezone_identifiers.go from an official IANA tzdata archive:
//
//	curl -fLO https://data.iana.org/time-zones/releases/tzdata2026c.tar.gz
//	go run generate_timezones.go tzdata2026c.tar.gz > timezone_identifiers.go
//
// Run from validate/. When updating tzdata, also update the version in timezone.go.
package main

import (
	"archive/tar"
	"bufio"
	"bytes"
	"compress/gzip"
	"crypto/sha256"
	"fmt"
	"go/format"
	"io"
	"os"
	"sort"
	"strings"
)

func main() {
	if len(os.Args) != 2 {
		panic("usage: go run generate_timezones.go tzdata<VERSION>.tar.gz")
	}
	archive, err := os.ReadFile(os.Args[1])
	check(err)
	zipped, err := gzip.NewReader(bytes.NewReader(archive))
	check(err)
	defer zipped.Close()
	reader := tar.NewReader(zipped)
	names := make(map[string]struct{})
	var version string
	for {
		header, err := reader.Next()
		if err == io.EOF {
			break
		}
		check(err)
		switch header.Name {
		case "version":
			data, err := io.ReadAll(reader)
			check(err)
			version = strings.TrimSpace(string(data))
		case "africa", "antarctica", "asia", "australasia", "europe", "northamerica", "southamerica", "etcetera", "backward":
			scanner := bufio.NewScanner(reader)
			for scanner.Scan() {
				fields := strings.Fields(scanner.Text())
				var name string
				if len(fields) >= 2 && fields[0] == "Zone" {
					name = fields[1]
				} else if len(fields) >= 3 && fields[0] == "Link" {
					name = fields[2]
				}
				if name == "UTC" || strings.Contains(name, "/") {
					names[name] = struct{}{}
				}
			}
			check(scanner.Err())
		}
	}
	if version == "" || len(names) == 0 {
		panic("archive is missing tzdata version or timezone identifiers")
	}
	keys := make([]string, 0, len(names))
	for name := range names {
		keys = append(keys, name)
	}
	sort.Strings(keys)
	var out bytes.Buffer
	fmt.Fprintln(&out, "// Code generated by generate_timezones.go; DO NOT EDIT.")
	fmt.Fprintf(&out, "// Source: https://data.iana.org/time-zones/releases/tzdata%s.tar.gz\n", version)
	fmt.Fprintf(&out, "// Archive SHA-256: %x\n", sha256.Sum256(archive))
	fmt.Fprintln(&out, "// Includes Zone and Link names containing a slash, plus UTC (including backward aliases).")
	fmt.Fprintln(&out, "\npackage validate\n\nvar timezoneIdentifiers = map[string]struct{}{")
	for _, name := range keys {
		fmt.Fprintf(&out, "%q: {},\n", name)
	}
	fmt.Fprintln(&out, "}")
	source, err := format.Source(out.Bytes())
	check(err)
	_, err = os.Stdout.Write(source)
	check(err)
}

func check(err error) {
	if err != nil {
		panic(err)
	}
}
